apiVersion: v1
kind: Service
metadata:
  name: nginx-internet
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: nginx-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80